### ISSUE TITLE
Simple formatting request

### ISSUE THREAD

**Issue by Shadetail** [SirCmpwn/SauceHunt#3]
Would be great if the formatting was changed so that
>Find the sauce yourself at https://saucenao.com ! 

is either removed (saucenao is featured in every subreddit sidebar anyways) or at least made much less obtrusive, like:

> ^^^\[~saucenao.com](https://saucenao.com)

**Comment by SirCmpwn** [comment]
I'll take a look at this within the next day or two.

**Comment by SirCmpwn** [comment]
Done.

**Comment by Shadetail** [comment]
:)
